### PR TITLE
Legal classification tasks (EurLex, UnfairTOS, and CaseHold)

### PR DESCRIPTION
**Pull request by pdasigi**
Notes:
- Both classification tasks are multi-label tasks, with a variable number of labels associated with each instance.
- Eurlex has a label set of size 21 and long contexts (~1750 tokens)
- UnfairTOS has a label set of size 8 and short contexts
- I included all the labels in the prompts for these tasks
- I am not sure about the `construct_requests` methods. I copied what seemed like the most common implementation in other tasks.

### CODE REVIEW

**Comment by OyvindTafjord** [comment]
Were you able to run this and look at sample input/output? Code like
```
return "Output all labels from the following list of EuroVoc Concepts: " + self.EUROVOC_CONCEPTS + \
" that can be applied to the following text. TEXT: " + doc["text"] + "\n" + "A:"
```
where `self.EUROVOC_CONCEPTS` is a list of string doesn't look like it would work? 

Btw, do we think a vanilla LM can produce valid output for a prompt like this? Even for an instruction-tuned model there should probably be an example answer in the prompt, showing you want it comma-separated or something (even though the documents might be too long to show a full example in the prompt)

**Comment by pdasigi** [comment]
@OyvindTafjord Thanks for pointing out the issue with the list of strings. I fixed it and tweaked the prompts a bit.

I am not sure if a vanilla LM is expected to do well on these multi-label classification tasks. The options are also presented as a comma separated list in the prompt, so it may not be too unreasonable to expect the output to be formatted similarly?
If we decide that these tasks are not informative, we can remove them later. I think it would be interesting to try these, both because they are in the legal domain, and also because of the multi-label format.

I also added another legal task, CaseHold, to this PR that is in an easier format, multiple choice QA. I mostly used the implementation of the ARC tasks for this one.

**Comment by OyvindTafjord** [comment]
Here's a command you can run to test this locally:
```
python catwalk/run_lm_eval.py  --model lm::pretrained=EleutherAI/pythia-160m,revision=step140000  \
--task eurlex --split validation  --full_output_file output.jsonl --metrics_file metrics.json \
--limit 5 --num_recorded_inputs 1 --model_max_length 2048
```
Trying this I got a couple of error messages which I could fix by changing the `process_results` function from:
```
    predicted_concepts = [result.strip() for result in results.split(",")]
    metrics = self.get_metrics(predicted_concepts, target_concepts)
    return metrics
```
to
```
    predicted_concepts = [result.strip() for result in results[0].split(",")]
    metrics = self.get_metrics(predicted_concepts, target_concepts)
    return {"f1": metrics}
```
(`results` comes back as a list, and the return value needs to be a dictionary, feel free to also add other metrics, like `p` and `r` if that might be useful, while `f1` might be the "primary_metric" reported).

Also, if you can estimate a max token count for the results, it's useful to add in the task definition, e.g.,
```
EleutherTask("eurlex", eleuther_metrics=True, model_args = {"max_gen_toks": 50})
```
in case it starts overgenerating nonsense (for this model it only generates `\n` for these 5 first examples, so immediately quits, so that's not so great... we don't have currently have an easy way to force a minimum number of tokens)

You can see sample input/output in the `output.jsonl` file, here's a way to display the prompt:
```
$ jq -r '.per_instance[0].model_input.greedy_until[0][0]' output.jsonl
Output all concepts from the list of EuroVoc concepts that can be applied to the text that follows. EUROVOC CONCEPTS: social questions, industry, finance, trade, business and competition, international relations, agriculture, forestry and fisheries, production, technology and research, transport, employment and working conditions, politics, law, education and communications, international organisations, energy, EUROPEAN UNION, science, agri-foodstuffs, geography, economics, environment TEXT: COMMISSION IMPLEMENTING REGULATION (EU) No 782/2012
of 28 August 2012
establishing the standard import values for determining the entry price of certain fruit and vegetables
THE EUROPEAN COMMISSION,
Havin....binding in its entirety and directly applicable in all Member States.
Done at Brussels, 28 August 2012.
A:
```
I would maybe put a newline or two before the "TEXT" and change "A:" to "Answer:" or "Concepts:" or something like that to make it a little clearer (although I think this task formulation will be very hard for non-instruction models).

**Comment by pdasigi** [comment]
Thanks for the detailed feedback and suggestions, @OyvindTafjord! I made the edits you suggested, except for
```
EleutherTask("eurlex", eleuther_metrics=True, model_args = {"max_gen_toks": 50})
```
`EleutherTask` does not seem to take a `model_args` argument. Perhaps there's a different way to set this limit? I searched the codebase, but I could not figure out how to do this.

**Comment by OyvindTafjord** [comment]
Sounds good. For the `max_gen_toks` you probably need to merge in the latest olmo-eval, then you should see a similar example for "drop" here: https://github.com/allenai/catwalk/blob/777b387f93b9b6ad9f2c0f33b5c2f3e352b25bae/catwalk/tasks/tasks_lm.py#L24

**Comment by pdasigi** [comment]
Thanks @OyvindTafjord! I added `max_gen_toks` for Eurlex and UnfairTOS.

**Review by OyvindTafjord — APPROVED** [review]
LGTM

**Pull request merged**
